spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/test
    username: postgres
    password: postgres
  jpa:
    properties:
      hibernate:
        hbm2ddl:
          auto: update
        dialect: org.hibernate.dialect.PostgreSQLDialect
        temp:
          use_jdbc_metadata_defaults: false
    show-sql: true
  redis:
    database: 0
      host: localhost
      port: 6379
      password: 123456
      timeout: 6000
      pool:
        max-active: 1000
        max-wait: -1
        max-idle: 10
        min-idle: 5
  jackson:
    serialization:
      fail-on-empty-beans: false
mybatis:
  config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath:mybatis/mapper/*.xml
  type-aliases-package: com.wu.sbdemo.shiro