spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://118.190.154.13:6180/test
    username: postgres
    password: wtlh@QWE123
  jpa:
    properties:
      hibernate:
        hbm2ddl:
          auto: update
        dialect: org.hibernate.dialect.ProgressDialect
        temp:
          use_jdbc_metadata_defaults: false
    show-sql: true
mybatis:
  config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath:mybatis/mapper/*.xml
  type-aliases-package: com.wu.sbdemo.mybatis